#!/bin/sh

BIN=../bin
NAME=PixelFactory
INPUT_CHANNEL=
INPUT_SOCKET=
OUTPUT_CHANNEL=INTERSECT
# OUTPUT_SOCKET=ipc:///tmp/feeds/intersect
OUTPUT_SOCKET=tcp://127.0.0.1:1313
echo $BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET
$BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET
