#!/bin/sh

BIN=../bin
NAME=Writer
INPUT_CHANNEL=PNG
INPUT_SOCKET=tcp://127.0.0.1:1308
OUTPUT_CHANNEL=
OUTPUT_SOCKET=
METADATA=foo.png

echo $BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET $METADATA
$BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET $METADATA
