#!/bin/sh

BIN=../bin
NAME=DepthChart
INPUT_CHANNEL=DEPTH
INPUT_SOCKET=tcp://127.0.0.1:1307
OUTPUT_CHANNEL=PNG
OUTPUT_SOCKET=tcp://127.0.0.1:1308

echo $BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET
$BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET
