#!/bin/sh

BIN=../bin
NAME=Feeder
INPUT_CHANNEL=PIZZA
INPUT_SOCKET=tcp://127.0.0.1:1308
OUTPUT_CHANNEL=
OUTPUT_SOCKET=
METADATA=pixels.txt

echo $BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET $METADATA
$BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET $METADATA
