#!/bin/sh

BIN=../bin
NAME=IntersectWith
INPUT_CHANNEL=INTERSECT
INPUT_SOCKET=tcp://127.0.0.1:1300
OUTPUT_CHANNEL=RESULT
OUTPUT_SOCKET=tcp://127.0.0.1:1301
METADATA=$1 # Note: You need to pass a world object for this to watch

echo $BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET $METADATA
$BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET $METADATA
