#!/bin/sh

BIN=../bin
NAME=Reflection
INPUT_CHANNEL=Shader
INPUT_SOCKET=tcp://127.0.0.1:1312
OUTPUT_CHANNEL=IntersectWith
OUTPUT_SOCKET=tcp://127.0.0.1:1314

echo $BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET
exec $BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET
