#!/bin/sh

BIN=../bin
NAME=Reflection
INPUT_CHANNEL=SHADE
INPUT_SOCKET=tcp://127.0.0.1:1312
OUTPUT_CHANNEL=INTERSECT
OUTPUT_SOCKET=tcp://127.0.0.1:1313

echo $BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET
$BIN/$NAME $NAME $INPUT_CHANNEL $INPUT_SOCKET $OUTPUT_CHANNEL $OUTPUT_SOCKET
